# Generated by Django 3.0.4 on 2020-05-16 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
